name: Deploy Pipeline Demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.1'

      - name: Build React App
        run: |
          cd client
          npm install
          npm run build

      - name: SSH Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            #!/bin/bash

            # Directory for this branch
            BRANCH_NAME="main"
            APP_DIR="/var/www/$BRANCH_NAME"

            mkdir -p $APP_DIR
            cd $APP_DIR

            # If repo does not exist, clone it
            if [ ! -d ".git" ]; then
              git clone -b $BRANCH_NAME git@github.com:prettify2025/pipeline-demo.git .
            else
              git fetch origin
              git reset --hard origin/$BRANCH_NAME
            fi

            # Load NVM and Node
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Install dependencies & build React app
            npm install
            cd client
            npm run build
            cd ..

            # Stop existing PM2 process if running
            if pm2 list | grep -q "$BRANCH_NAME"; then
              pm2 delete "$BRANCH_NAME" || true
            fi

            # Start Express server via PM2
            pm2 start server/index.js --name "$BRANCH_NAME"

            # Save PM2 process list
            pm2 save

