name: Deploy Pipeline Demo

on:
  push:
    branches:
      - main
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            #!/bin/bash

            # Extract branch name
            BRANCH_NAME=${GITHUB_REF#refs/heads/}

            # Deployment folder
            APP_DIR="/var/www/pipeline-demo.$BRANCH_NAME"
            mkdir -p "$APP_DIR"
            cd "$APP_DIR" || exit 1

            # Initialize git if not exists
            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:prettify2025/pipeline-demo.git
            fi

            # Pull latest code
            git fetch origin
            git checkout -B "$BRANCH_NAME"
            git reset --hard "origin/$BRANCH_NAME"

            # Load NVM and Node.js
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            # Install dependencies and build client
            npm install
            npm run build

            # Start/restart PM2 process
            if pm2 describe "$BRANCH_NAME" > /dev/null 2>&1; then
              pm2 restart "$BRANCH_NAME"
            else
              pm2 start server/index.js --name "$BRANCH_NAME"
            fi
            pm2 save

