name: Auto Deploy

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 103.152.79.30
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22919
          debug: true
          script: |
            cd /var/www/pipeline-demo
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            npm install
            npm run build
            pm2 restart pipeline-demo || pm2 start server/index.js --name pipeline-demo

